### ISSUE TITLE
Crashes on 0.18

### ISSUE THREAD

**Issue by arik123** [veger/TLBE#1]
Error while running event TLBE::on_tick (ID 0)
__TLBE__/scripts/main.lua:11: attempt to index local 'playerSettings' (a nil value)
stack traceback:
	__TLBE__/scripts/main.lua:11: in function <__TLBE__/scripts/main.lua:8>

**Comment by H4nSolo** [comment]
yep me too

I want to test the Mod but after downloding and installing it from the Mod Website of Facotrio, a can't load any Savegames ^^

[Image of the Error](https://imgur.com/8F8Xmtx)

Game Version: 0.18.32
Installed Mods: 110 (without the base Mod)


List of Mods:

> 
> 1: 2x2-Chest
> 2: A Sea Block Config
> 3: aaa-log-active-mods
> 4: Advanced-Solar
> 5: AfraidOfTheDark
> 6: angels-smelting-extended
> 7: angelsaddons-oresilos
> 8: angelsaddons-petrotrain
> 9: angelsaddons-pressuretanks
> 10: angelsaddons-warehouses
> 11: angelsbioprocessing
> 12: angelsindustries
> 13: angelspetrochem
> 14: angelsrefining
> 15: angelssmelting
> 16: AutoDeconstruct
> 17: beautiful_bridge_railway
> 18: belt-reverser
> 19: Better-Power-Armor-Grid
> 20: BigBags
> 21: BigFluidWagon
> 22: BlueprintExtensions
> 23: blueprint_flip_and_turn
> 24: bobassembly
> 25: bobelectronics
> 26: bobenemies
> 27: bobinserters
> 28: boblibrary
> 29: boblogistics
> 30: bobmining
> 31: bobmods_gfxtweak
> 32: bobmodules
> 33: bobplates
> 34: bobpower
> 35: bobrevamp
> 36: bobtech
> 37: bobvehicleequipment
> 38: bobwarfare
> 39: ChangeMapSettings
> 40: CircuitProcessing
> 41: Compilatron
> 42: Crafting_Speed_Research
> 43: DragonIndustries
> 44: easy-wind-turbine
> 45: EasyCreative
> 46: Electric Furnaces
> 47: EnableResearchQueue
> 48: enhanced-pipette
> 49: even-distribution
> 50: even-longer-inserters
> 51: Exoskeleton Mark II
> 52: Explosive Excavation
> 53: factorio-reach
> 54: Factorissimo2
> 55: FastLongInserters
> 56: flib
> 57: Flow Control
> 58: fluid-void-extra
> 59: FluidFilter
> 60: FluidMustFlow
> 61: fluid_permutations
> 62: FNEI
> 63: HandyHands
> 64: helmod
> 65: industrial-engineering
> 66: infinite_buffer_fluid_tank
> 67: Inventory Sensor
> 68: jetpack
> 69: KS_Power
> 70: LandfillPainting
> 71: LaneBalancer
> 72: LoaderRedux
> 73: LogisticTrainNetwork
> 74: LtnManager
> 75: LTN_Combinator
> 76: manual-inventory-sort
> 77: miniloader
> 78: Nanobots
> 79: nice-try-train
> 80: nixie-tubes
> 81: NoRespawnGun
> 82: Noxys_Waterfill
> 83: Nuclear Fuel
> 84: OpteraLib
> 85: Orphan Finder
> 86: PavementDriveAssist
> 87: PersonalTeleporter
> 88: Power Armor MK3
> 89: qol_research
> 90: railloader
> 91: RaiLuaLib
> 92: reverse-factory
> 93: ScienceCostTweakerM
> 94: SeaBlock
> 95: ShinyAngelGFX
> 96: ShinyBobGFX
> 97: some-corpsemarker
> 98: SpaceMod
> 99: Squeak Through
> 100: stdlib
> 101: StorageTank2
> 102: TarawindBeaconsRE
> 103: Teleporters
> 104: textplates
> 105: TimeTools
> 106: TLBE
> 107: UltimateBelts_Owoshima_And_Pankeko-Mod
> 108: VehicleSnap
> 109: VoidChestPlus
> 110: Warehousing

pls fix that ;-)

**Comment by veger** [comment]
Hi

Thank you for trying my mod :smile: 

hm... looks like initialization of the mod is not working (it does for me, but I only tried a single player 'freeplay'.
Which type of game are you trying?

(I am all new to creating mods, so I though I initialized the required variables properly, but maybe only for freeplay?)

**Comment by veger** [comment]
never mind, I tried a new game myself and also have the error... :disappointed:  (guess I meesed up some change during recording of the demo and never tried a new game after it)

I'll fix and make a release soon

**Comment by veger** [comment]
The commit should fix the issue of @H4nSolo as it did not initialize when loaded into existing games (I could reproduce this scenario and now it worked for me)

**Comment by veger** [comment]
@H4nSolo BTW the mod does not know the size of an _existing_ base, so you'd need to build something in each corner in order for the mod to make screenshots of your complete base.

**Comment by H4nSolo** [comment]
yep its fixed ;)

Thx for you work and have a nice day

**Comment by veger** [comment]
Thanks for reporting, I uploaded the release to the mod portal.

I'll leave the report open to see if it is fixed for @arik123 as well.

**Comment by H4nSolo** [comment]
ok but now it makes endles sreenshot of my position and actions ^^

https://imgur.com/a/yOgaHuo <--- ingame

https://imgur.com/J3YLnks <----- Screenshot Folder

**Comment by H4nSolo** [comment]
Do you want my modpack and savegame for testing?

**Comment by veger** [comment]
If you have default settings, you are recording with 25 frames per second, with a 'speed increase' of 1.5, so you'd end up with 25/1.5 = ~17 screenshots per second..! (not a real timelapse, more a 'fast rewind' :wink: )

Try increasing 'speed increase' to 60 (1 screenshot per minute -> ~1 per 2.4 second with 25fps), or even 120 (5 screenshot per 5 @ 25fps)
But yes, iamount of mages will grow fast... The 8 hour play for my demo resulted in over 7000 screenshots (using 120 speed increase)

**Comment by veger** [comment]
BTW the numbers in the image names are the game ticks on which the screenshots were taken, so in your case every 24 ticks a screenshot was taken (which is about 3 per second, as a second has 60 game ticks)

**Comment by arik123** [comment]
Works great for me, seems to work even on multiplayer 😄 Great mod, gonna use it on my next playthrough. Also, I would like to suggest you to set a bit more sensible default values.

**Comment by veger** [comment]
>  seems to work even on multiplayer

This was on my todo list to check, thanks for reporting :smile: 

> I would like to suggest you to set a bit more sensible default values.

You have suggestions? (feel free to suggest :wink: ) Or it was more in general?

**Comment by arik123** [comment]
Make default capture rate 1/min or something like that, and turn chat spam off, maybe just print "Capture started" or something like that.

**Comment by veger** [comment]
Thank you for your suggestions

> default capture rate 1/min or something like that

Makes sense as a default yes

> turn chat spam off, maybe just print "Capture started" or something like that.

I am going to completely disable, as it does not add any value (I started it as debug purpose, and then got annoyed by it :wink: ) (see #4)
