### ISSUE TITLE
Enable camera (taking screenshots) by default

### ISSUE THREAD

**Issue by veger** [veger/TLBE#16]
It might be less confusing if the camera takes screenshots by default.
Additionally, a (map) settings can be added to disable this default state if someone for some reason does not want the camera to be enabled by default (e.g. when changes to the camera/trackers are required before taking screenshots)

**Comment by arnemertz** [comment]
There are pros and cons in enabling it by default.

Pro: new users don't have to figure out that they have to enable it, so they will have the recording from the start.
Con: it will produce a considerable amount of image files maybe without the user noticing it. I have 7.4 GB for just one hour of playing in my current save. Flooding the drive like that should at least come with a warning.

My take: disable the camera by default, but add a kind of "greeting message" on a new game to remind users to enable cameras if they want to (or disable the mod if it's active by accident)

**Comment by veger** [comment]
Taking screenshots takes space true, this should be clear when loading/installing the mod I guess?

But, starting to take screenshot immediately, does not make sense as the camera is not configured yet (resolution, frame rate, etc), so the screenshots are most likely worthless...

I'll add a warning message to hint (new) players to enable the camera.
