### ISSUE TITLE
(better) support loading into existing game

### ISSUE THREAD

**Issue by veger** [veger/TLBE#2]
Ccurrently TBLE does not know the size of an existing factory when loading into a new game.
It would be good to have an option to (re)set the base size.

Could be done with [`LuaSurface.find_entities()`](https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.find_entities) (might take a while when base is big...)

**Comment by arik123** [comment]
Maybe a notification for the player could be usefull: "Factory size is unknown, please place something to each corner of your factory"

**Comment by veger** [comment]
good idea :+1:
