### ISSUE TITLE
Timelapses on server level

### ISSUE THREAD

**Issue by veger** [veger/TLBE#21]
_From https://mods.factorio.com/mod/TLBE/discussion/602693b06e656b8e73ffe544_

Is it even possible to run mods on servers?
And making sure it only runs if players are online only?

**Comment by fortysixandtwo** [comment]
I would be amazed if this could be run on the server. Of course an admin would need to be able to setup cameras using the UI (just as if it were the client mod).

The main problem I see is: Does the server even have any rendering capabilities? I mean.. it's a server and all ;)
Can you point me to the relevant lines in the code where the screenshot is taken? Is that https://github.com/veger/TLBE/blob/master/scripts/main.lua#L55 ?
If so: https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.take_screenshot
> Note: If Factorio is running headless, this function will do nothing.

**Comment by veger** [comment]
Yes, so as I guessed it is not even possible as it is unable to render the screenshots...

Best alternative would be to a passive/bot player that is always online to take the screenshots for a server game
