### ISSUE TITLE
Area tracker is not updating its position and size

### ISSUE THREAD

**Issue by prescientmoon** [veger/TLBE#27]
![image](https://user-images.githubusercontent.com/39400800/137288972-acc039a1-e73d-47a1-9836-8f7d9da892e1.png)

As you can see, the size seems to be kinda broken...

**Comment by prescientmoon** [comment]
it keeps taking screenshots of this one area
![00686016-bity](https://user-images.githubusercontent.com/39400800/137289362-e225d13a-259b-46df-9dc2-e0b2b04d6f2f.png)

**Comment by veger** [comment]
I am using the area tracker myself and it works. (at least for me :wink: )
Are you sure it is the active tracker on a/the camera?

The camera uses trackers to define the position and zoom factor of the screenshots, so a tracker on itself is not doing much (the base tracker, for example, keeps track of new buildings).

**Comment by prescientmoon** [comment]
hmm, perhaps I am doing something wrong: 
![image](https://user-images.githubusercontent.com/39400800/137297598-dd6ae7dc-32bc-4ed0-ac37-81eed49569c1.png)
![image](https://user-images.githubusercontent.com/39400800/137297667-d2f58599-faea-448f-9104-bcdbe2632422.png)

**Comment by veger** [comment]
It all looks good on a first glance.
* Are other trackers working correctly? Or are they all failing to work?
* Are the cameras globally paused? (see tool button in the toolbar or use CONTROL + SHIFT + P shortcut)

I'll take a look when I am back home (in the evening) to see if I can reproduce the issue

**Comment by prescientmoon** [comment]
Not all the cameras are globally paused

It seems like all trackers are failing to work 🤔

**Comment by prescientmoon** [comment]
In the meantime, is there any good way to "reset" the state of the mod? Deleting and reinstalling it from the mod menu doesn't seem to do the job

**Comment by veger** [comment]
I was able to reproduce that the 'Area Tracker is misbehaving just as you showed:
1. `Center` and `Size` are not getting updated when changing top/right and bottom/left coordinates
2. Camera only grabs the tracker position when a new one is added and the Area Tracker is added to it. (so it is also pretty much broken)

The other trackers do work for me though, when they are active (they have the play icon in front of them).
Can you see any screenshots being taken in the [`script-output`](https://wiki.factorio.com/Application_directory)`/tlbe` folder?

**Comment by veger** [comment]
hm... weird now that I do a more thorough test it is working properly (again)

_Edit_: Oh... now I see your issue:

Your `Right` coordinate is left of your `Left` coordinate... This is not allowed (hence the red color).
If you swap their values, the red color should disappear and the center/size of the tracker should be calculated properly.

(I guess I messed up as well when quickly testing before)

**Comment by prescientmoon** [comment]
Ohhhhh, I'm stupid :p

Imma try it tomorrow

**Comment by veger** [comment]
no problem! also took me a while to see the issue :smile:

**Comment by prescientmoon** [comment]
Yep, works as expected!
