### ISSUE TITLE
Testing with ridiculous screenshot sizes

### ISSUE THREAD

**Issue by bloxanne123** [veger/TLBE#28]
more or less the title
I'm a madman, so when I looked at individual images and saw a pixelated blob when zoomed in, I was annoyed. I'd upload images but they've been deleted. For reference, they were made at 1440p. Keep in mind that the screenshots all have very little difference (no new chunks were explored/visited, I only built some stuff)

The small issue I have with this: anything larger than 4k is not taken properly. When I went to 8k, I played for five minutes, yet in the timelapse folder there were only two 8k images. I'll blame this on VRAM...I only have two and my SSD is fast enough for this.

ok so the game crashed with 16k images and the game at max settings, since I only have 2GB of it
![image](https://user-images.githubusercontent.com/63023773/139514296-c89839c0-0630-4d7e-8e50-9992b0d8b25d.png)

4k Image:
(when I find out how to insert 21mb images I'll post it)

8k Image: 
(when I find out how to insert 84mb images I'll post it)

16k Image:
(when I find out how to insert 330mb images I'll post it)

**Comment by bloxanne123** [comment]
One more thing: Do the ingame settings for resolution of sprites and atlas affect screenshots?

**Comment by veger** [comment]
For the mod the screenshot size doesn't matter, so screenshot not being taken or crashing the game is out of the influence of the mod.

Of course for the game itself it matters... Especially on (V)RAM I suppose. And yes quality settings, atlas size, etc (I suppose all on the graphical settings), will influence this as well. It is (all) using more or less (V)RAM and thus influences the maount left to take the actual screenshots.

I guess you'd better go to the Factorio forums or Reddit to find more experts on this area to find out how to maximize the resolution. :smile: (altough I am afraid the conclusion is to get better/more hardware)

PS There is [proof](https://www.youtube.com/watch?v=dY2nxVNBHQs) that 8K screenshots work, I don't know about 16K... :stuck_out_tongue:

**Comment by bloxanne123** [comment]
But will the atlas size and quality affect how detailed stuff is in the screenshots?

**Comment by bloxanne123** [comment]
And also I don't think I'm *ever* touching 16k again.
I might TRY 32k but that's INSANE

**Comment by veger** [comment]
> But will the atlas size and quality affect how detailed stuff is in the screenshots?

AFAIK (I am certainly not a graphic-pipeline expert) atlas size defines how large each spritesheets (atlas) is. This influences how much spritesheets the game needs (not the quality, that is another setting) to be able to render all sprites. The optimum size of a spritesheet depends on several factors, where amount of VRAM is probably the most important (as it then would be able to fit 1 _huge_ spritesheet, instead of swapping multiple smaller ones while rendering). Some other factors that pop in mind: amount of mods (defines total amount of sprites), memory bandwidth/speed, throughput RAM->VRAM, and probably quite some more.

For example, if you have some sprites (let's assume of the same size to keep things simple) and they fit one one spritesheet. By decreasing the size of the spritesheet by 4 (halved width and height), you'd suddenly need 4 spritesheets to fit all sprites.

**Comment by bloxanne123** [comment]
interesting! I know nothing about these topics, thank you for explaining
Maybe once I get a device with 6GB of VRAM it will function far better...I'll keep testing in the meantime

**Comment by bloxanne123** [comment]
So I tested with a 4GB VRAM laptop and an i7-10850H or something 
It has a Quadro T2000
Interestingly, the lag was _not_ due to VRAM being taken up at 4k screenshots and the base game at max (which hovered at 2.2GB VRAM usage which is just out of reach for my laptop -_-)
I have no clue what the issue is. Maybe the SSD but it's an SSD so I sort of doubt it. I'll test more, but I think it could also be the CPU...?

I have a question for you from someone else I asked about this.

> Are you writing to storage directly from VRAM?
> If so, try copying it to a CPU memory buffer before you touch IO.

I don't know how the mod does it.
What I feel the mod does but probably doesn't is write directly to storage from VRAM because that sounds simpler lol.

**Comment by veger** [comment]
The mod uses the Factorio API to make a screenshot, and TBH I don't know how the Wube devs implemented this.

I do know that no matter what the screenshot needs processing (rendering all tiles that are in the screenshot), which takes CPU and (V)RAM.
If you feel that there is something wrong or could be improved (performance wise), then I guess it would be best to go to the Factorio forums and ask/tell the devs about it. There is a bug reporting section IIRC on which more knowledgeable people are around :smile:

**Comment by bloxanne123** [comment]
Okie doke, thanks!

**Comment by bloxanne123** [comment]
1080p screenshots lag just a bit on that laptop, and they lag a teensy bit more on mine. I'd chalk that up to how the Wube devs implemented the screenshot feature...trying to confirm/deny that though.

**Comment by drdozer** [comment]
Can we mark this as "not our problem - blame WUBE" and close?

**Comment by veger** [comment]
good plan :rofl:
