### ISSUE TITLE
Is it possible to write to an external drive?

### ISSUE THREAD

**Issue by bloxanne123** [veger/TLBE#29]
I may be acquiring a 1TB SSD in the future, and I would like to be able to write screenshots to the SSD when it's plugged in or if it's not plugged in, write them to the normal folder. 

Is it possible to tell the mod to write screenshots to a designated spot on the external SSD? I'd transfer manually but my laptop only has USB 2.0...so 57 mb/s is quite slow to do via manual transfer. If I write directly to the SSD, will the images properly save? (I don't want any incomplete files)

**Comment by veger** [comment]
Not easily...Factorio has a default folder where mods can write their data (screenshots in the case of TLBE). It cannot be changed (I guess for security reasons).
The only thing that is possible is to create a symbolic link (I guess this works, never tried) when the SSD is plugged in and get rid of if when it is disconnected... Not very convenient but it might work..?

You can ask on Factorio forums if the devs are willing to allow mods to write to other folders, but I do not think they will agree/implement such a feature...

**Comment by drdozer** [comment]
Can we mark this as WUBE's issue and close?

**Comment by veger** [comment]
I marked it with the FAQ label, as it gets asked quite a bit, but it is indeed (purposely) limited by WUBE.

I left it open to (hopefully) prevent duplicate issues, until I found time/priority to actually write the FAQ

**Comment by veger** [comment]
There is a [FAQ](../blob/master//FAQ.md) now! :smile:
