### ISSUE TITLE
Yafc fork

### ISSUE THREAD

**Issue by LoneWolfProductions** [veger/TLBE#30]
I'm very sorry to contact oyu through here,

but your modified version of YAFC is throwing this error.
It seems something is reffering to your folder structure on your HD?

![Annotation 2022-01-26 131442](https://user-images.githubusercontent.com/30441722/151161311-6b5aa97e-95cf-44f9-9b9d-fb14d9713cb6.png)

**Comment by veger** [comment]
No problem, I see that the issues were not enabled on the fork. (I assumed they were by default)

I copies the report to https://github.com/veger/yafc/issues/1
