### ISSUE TITLE
Night-time screenshots

### ISSUE THREAD

**Issue by veger** [veger/TLBE#31]
From https://mods.factorio.com/mod/TLBE/discussion/622d132dce7362caa32e5573:

> Do you have any plans to enable screenshot to be taken as is during night? I.e. the nights actually being dark.
> I'm using a flashlight mod and would love to see the glowing dots from the ovens in the pitch blackness.

**Comment by veger** [comment]
Thank you for your feature request, I never thought of the implications of a night-time timelapse (I only thought about visibility :smile: )

I am currently on a hiatus (Py/AL broke me atm :stuck_out_tongue: ), but I will recover and come back!

The feature itself is not hard, you can [set the `daytime` when taking screenshots.](https://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.take_screenshot). Only thing is that you probably want to be able to gradually change from day to night to day I suppose? (as a full night time timelapse might be a bit too much?) Implementing this is a (little bit) more work.

So feel free to provide a PR if you know a bit about Lua, otherwise you'd have to wait (or find someone else to make the PR :wink: )

**Comment by drdozer** [comment]
see pull request #34

**Comment by veger** [comment]
Enhancement will be available in next release

**Comment by veger** [comment]
Released in v1.4.5
