### ISSUE TITLE
Recording status alert

### ISSUE THREAD

**Issue by veger** [veger/TLBE#41]
From https://mods.factorio.com/mod/TLBE/discussion/6498a5ed070072bbaa7d044c

> recording status alert (which can be turned off) including - not recording, recording, panning

**Comment by veger** [comment]
Status reports could also include (change) of tracker?

**Comment by veger** [comment]
Easiest would be to print (chat) messages when something changes, but I guess it would (also) be nice to have it on screen (like FPS/UPS, evo, etc info)?

Maybe implement both and make it configurable by the user to have it off, in chat, or on-screen

**Comment by theotherbigfoot** [comment]
I really like this idea. Maybe all it needs is a series of lights in the main timelapse menu. 'Normal recording', 'transition underway', 'transition complete'

**Comment by drdozer** [comment]
is it possible to do this with a reskin of the "pause all cameras" button? So it would switch between icons to indicate recording/transition status?  I don't know enough to know if buttons can have their icons changed during the game.

**Comment by veger** [comment]
That would be nice, but I doubt it is possible as prototypes are constructed/managed in the ['data stage'](https://lua-api.factorio.com/latest/Data-Lifecycle.html) only.

**Comment by veger** [comment]
Experimented with [custom alerts](https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.add_custom_alert), but those require an entity to get tied to (can fake one, but still). And they disappear after a while (so we'd need to spam them over and over)
Not a very nice/clean solution

**Comment by veger** [comment]
Decided to make use of [Stats GUI](https://mods.factorio.com/mod/StatsGui).
It is flexible and looks clean (in code and in the game)

I could not think of a good indicator that actually works (having a 'lamp' in some corner of the screen didn't look nice in my mind, especially with multiple cameras). Adding support for Stats GUI is easy and could be replaced when a better (graphical) UI have been figured out.

**Comment by veger** [comment]
![Screenshot_20230704_120601](https://github.com/veger/TLBE/assets/171827/0851055f-c649-4d6a-83b1-bcd4541e201b)

@drdozer  Feel free to try it from branch [issue-41_show-camera-stats](https://github.com/veger/TLBE/tree/issue-41_show-camera-stats).
If you have/had something different in mind, let me know :smile:

**Comment by veger** [comment]
The feature will be included in the next release

**Comment by drdozer** [comment]
Is your policy to leave tickets open until the release, or close them when the final merge happens? I don't much mind which but would like to know what the policy is.

**Comment by veger** [comment]
until after the release

**Comment by veger** [comment]
Released in v1.5.0
