### ISSUE TITLE
Did you update to v2.0.1? I think I fixed this one in #62

### ISSUE THREAD

**Issue by theotherbigfoot** [veger/TLBE#64]
Did you update to v2.0.1? I think I fixed this one in #62

_Originally posted by @veger in https://github.com/veger/TLBE/issues/61#issuecomment-2431917164_
            
Fully updated yes. 

I'm on Gleba and I try and set up a new area or base tracker and it crashes. I probably should have mentioned this at the beginning

**Comment by veger** [comment]
So it is resolved (https://github.com/veger/TLBE/issues/61#issuecomment-2432599262) or is this about another issue?

**Comment by theotherbigfoot** [comment]
No, this post was a mistake
