### ISSUE TITLE
Error while running event 

### ISSUE THREAD

**Issue by CarlosTorch** [veger/TLBE#67]
Error while running event StatsGui::on_player_created (ID 27)
Error when running interface function TLBE.recording_sensor: __TLBE__/scripts/camera.lua:496: attempt to index local 'playerSettings' (a nil value)
stack traceback:
	__TLBE__/scripts/camera.lua:496: in function <__TLBE__/scripts/camera.lua:493>
stack traceback:
	[C]: in function 'call'
	__StatsGui__/control.lua:157: in function 'sensor'
	__StatsGui__/scripts/stats-gui.lua:47: in function 'update'
	__StatsGui__/scripts/stats-gui.lua:25: in function 'build'
	__StatsGui__/scripts/player-data.lua:34: in function 'refresh'
	__StatsGui__/control.lua:40: in function <__StatsGui__/control.lua:37>

**Comment by veger** [comment]
Thanks for the report, it is a (newly introduced) incompatibility between TLBE and StatsGUI.

It is fixed in the next release (when you turn off the StatsGUI mod the issue won't show up, ofc if you want/will to so)

**Comment by veger** [comment]
Fixed in v2.0.4
