### ISSUE TITLE
[question] about this mod

### ISSUE THREAD

**Issue by Fr-Dae** [veger/TLBE#68]
hello, i have some question about your mods, in advance, thanks you for your time and your works.

- work with other planet / space platform ?
- work on effective savegame ? 
I currently make a manual save every hour of play.
then after a game session I manually open each save and use the command ` /c game.take_screenshot{resolution = {x = 10500, y = 10000}, position= {290 , -8}, zoom = 0.3, show_entity_info = true}`. 
I make one for day and one for night, then I rename the files and move them to a folder.

Could your mod help me automate this?

**Comment by veger** [comment]
Hi

> work with other planet / space platform ?

Yes, those are 'surfaces', which are supported by TLBE.
This is also reported here: https://github.com/veger/TLBE/issues/61#issuecomment-2427857738

>  make one for day and one for night, then I rename the files and move them to a folder.

I see two possibilities:
1. use the [take screenshot](https://github.com/veger/TLBE/blob/master/graphics/take-screenshot-32.png) button when one hour is passed to take a screenshot. TLBE is capable of taking a screenshot at full day. So if you plan it when it is night, you can (manually) take both screenshots. (protip: set up 2 camera so the filenames are unique/correct to distinguish both)
2. Set up the (2) camera(s) to take a screenshot is a very slow interval (1 hour) and it will only make a screenshot every hour.

For both possibilities you need to setup a 'tracker' to tell the camera of what area to take the screenshots. e.g. use AreaTracker to define the area manually with your coordinates, or some other tracker to (also) automate this.
 (protip: you can use the same tracker for both cameras, so have identical screenshots!)

**Comment by Fr-Dae** [comment]
it's a bit confusing, I'll have to do some tests to understand.
At the moment I have 200Mio files that cover my entire database in 0.3 zoom.

**Comment by veger** [comment]
Depending on the use-case it can be complex yes (especially with 'fancy' timelapses).
If there are things that you would like to see added to cover/help out with your ideas, let me know in a (separate) issue and we can see how to implement it!
